### ISSUE TITLE
Prompt views do not retain state on screen orientation

### ISSUE THREAD

**Issue by jiawenzhang** [stkent/amplify#131]

**Comment by stkent** [comment]
Thanks for the report! I'll prioritize this for the next patch release (1.1.1).

**Comment by stkent** [comment]
I have this mostly-done locally; I still need to:

- [ ] restore the ability for library consumers to listen for prompt view events;
- [ ] track down and fix a memory leak that manifests on orientation change;
- [ ] finish updating the README.

**Comment by stkent** [comment]
Going to rename this milestone from 1.1.1 to 1.2.0 since there are non-trivial API changes involved. Bumping all other milestones accordingly.

**Comment by jiawenzhang** [comment]
look forward to 1.2.0 releasing

**Comment by stkent** [comment]
Aiming to have this released by April 1 :-)

**Comment by stkent** [comment]
@jiawenzhang v1.2.0 shipped today, please try it out and let me know how it's working for you!
