### ISSUE TITLE
Have thanks view automatically dismiss

### ISSUE THREAD

**Issue by jiawenzhang** [stkent/amplify#132]

**Comment by stkent** [comment]
Interesting suggestion. My first thought on how to support this would be to add a `getRootViewGroup` method to the `IPromptView` interface. This would then allow library users to do something like the following:

```java
Amplify.get(context).promptIfReady(activity, promptView, new IEventListener<PromptViewEvent>() {
    @Override
    public void notifyEventTriggered(@NonNull final PromptViewEvent event) {
        if (event == PromptViewEvent.THANKS_SHOWN) {
            final Handler handler = new Handler();
            handler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    final View promptViewRootView = promptView.getParent();
                    // todo: apply your own custom animation here
                    ((ViewGroup) promptViewRootView.getParent()).removeView(promptViewRootView);
                }
            }, 2000);
        }
    }
});
```

Would that allow you to accomplish what you had in mind?

**Comment by jiawenzhang** [comment]
This will work. An ideal approach would be hiding all these logics inside
the lib and expose a configure option like dismissThankyouTime for user to
set

**Comment by stkent** [comment]
Cool, thanks for replying! I'll think about the configuration option that you suggest, and see how that fits with the current library structure. Scheduling this for 1.2.0 :)

**Comment by jiawenzhang** [comment]
That will be very helpful. Thank you!

**Comment by stkent** [comment]
This got moved to 1.4.0 which is the next planned feature release.
