### ISSUE TITLE
Dismiss Listener

### ISSUE THREAD

**Issue by eoinfogarty** [stkent/amplify#134]
I want to use the prompt view in a recycler view. The problem I have is when the prompt is dismissed I am left with a gap in my recyclerview where the prompt used to be. So I need some kind of hook so I can notify data set changed on my adapter to resize my recyclerview. Is this possible?

**Comment by eoinfogarty** [comment]
Ah I can see this code now, sorry for the noise

``` java 
Amplify.get(this).promptIfReady(this, promptView, new IEventListener<PromptViewEvent>() {
    @Override
    public void notifyEventTriggered(@NonNull final PromptViewEvent event) {
        AnalyticsTracker.notifyOfEvent(event);

        if (event == PromptViewEvent.PROMPT_SHOWN) {
            relatedView.setVisibility(VISIBLE);
        } else if (event == PromptViewEvent.PROMPT_DISMISSED) {
            relatedView.setVisibility(GONE);
        }
    }
});
```

**Comment by stkent** [comment]
No problem, let me know if you run into any other issues with this! The way you set up that listener will be changing slightly in version 1.1.1, but the provided functionality will be identical :)
