### ISSUE TITLE
Does my app has to be open source to use your library?

### ISSUE THREAD

**Issue by dirhem** [stkent/amplify#141]
I have a closed source app and I want to use your library inside it. Is it allowed? If so where should I put the license?

**Comment by stkent** [comment]
Hi there! The short answers are:

- yes, you can use this (and any other Apache 2.0 licensed libraries) in your closed source application as long as you provide attribution and a copy of the license;
- the most popular option that I've seen for satisfying the above requirements is to include a list of all open source libraries with the text of their respective licenses in an "About" or "Licenses" page of your application.

For example, you can find the Gmail app's open source attributions page by tapping

> Hamburger menu -> Help & Feedback -> Overflow menu -> Open source licenses

<img src="https://cloud.githubusercontent.com/assets/6463980/14316949/d62cfc8a-fbd3-11e5-96a1-aaac8476bba3.png" width="50%" />

Simpler apps normally link directly to an equivalent screen from their main or overflow menus.

Here's [a friendlier interpretation of the Apache licenses](http://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN) from the Apache Software Foundation themselves. The "About" or "Licenses" page described above takes care of attribution and inclusion of the license text :)
