### ISSUE TITLE
Check if view is being rendered by Android Studio Layout Preview Editor

### ISSUE THREAD

**Issue by drjunior** [stkent/amplify#152]
Rendering warnings:

The following classes could not be instantiated:
- com.github.stkent.amplify.prompt.DefaultLayoutPromptView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE  Exception Details java.lang.IllegalStateException: You must call initSharedInstance before calling getSharedInstance.   at com.github.stkent.amplify.tracking.Amplify.getSharedInstance(Amplify.java:108)   at com.github.stkent.amplify.prompt.BasePromptView.<init>(BasePromptView.java:116)   at

As the AS Layout Preview Editor has no access to the shared preferences it's necessary to check if view is in "edit mode" using the View.isInEditMode() and avoid those kind of calls that are not available when on "edit mode".

**Comment by stkent** [comment]
Good call, I'll tag this as an enhancement!
