### ISSUE TITLE
USER_GAVE_FEEDBACK and USER_DECLINED_FEEDBACK is gone?

### ISSUE THREAD

**Issue by jiawenzhang** [stkent/amplify#153]
We used to have these two events and they are very useful for sending app analytics. But they are gone in the latest version. Is there any way to bring them back?

**Comment by stkent** [comment]
Thanks for the report! This is a little puzzling. I still see those events being triggered in code in v1.3.1:

https://github.com/stkent/amplify/blob/1.3.1/amplify/src/main/java/com/github/stkent/amplify/prompt/PromptPresenter.java#L122

and

https://github.com/stkent/amplify/blob/1.3.1/amplify/src/main/java/com/github/stkent/amplify/prompt/PromptPresenter.java#L138

A few things that spring to mind to check right away:

- are you adding your own `IEventListener` instance to your `IPromptView` instance _before_ calling `Amplify.getSharedInstance().promptIfReady(promptView);`? See example below for the expected sequence:

``` java
DefaultLayoutPromptView promptView = (DefaultLayoutPromptView) findViewById(R.id.prompt_view);

promptView.addPromptEventListener(new IEventListener() {
    @Override
    public void notifyEventTriggered(@NonNull final IEvent event) {
        AnalyticsTracker.reportPromptEvent(event);
    }
});

Amplify.getSharedInstance().promptIfReady(promptView);
```

- are you receiving any events at all in your `IEventListener` instance? (For example, are `USER_INDICATED_POSITIVE_OPINION` events being reported to your listener? Are `THANKS_SHOWN` events being reported to your listener?)

- is behavior different before/after a configuration change?

Please check the above and reply to let me know how you get on :)

**Comment by stkent** [comment]
@jiawenzhang any updates on this from your end?

**Comment by stkent** [comment]
Closing, insufficient information provided.
