### ISSUE TITLE
"Thank you for feedback" message not dismissing

### ISSUE THREAD

**Issue by jamieomatthews** [stkent/amplify#155]
I'm just messing around with the prompt right now, and I'm seeing a strange issue in the emulator.  The last window "Thank you for feedback" never dismisses, even after going to another activity and back.  

The flow I do to reproduce is:
Enjoying the app -> No
Would you like to send feedback -> Sure
"Thank you for feedback" -> Does not dismiss

Alternatively it can be caused as:
Enjoying the app -> Yes
Would you like to rate -> Yes
(come back to the app)
"Thank you for feedback" -> Does not dismiss

Heres my rules for display:

Application.java

`Amplify.initSharedInstance(this)
                .setFeedbackEmailAddress(Config.RATING_CONTACT_EMAIL)
                .setAlwaysShow(true);`

Is this only happening with .setAlwaysShow() maybe?  Or - could it be because the emulator doesn't have an email client configured?

**Comment by stkent** [comment]
Hi Jamie,

Thanks for the report! 

First thing to check: are you using the latest version of the library (currently v1.3.1)? If not, please update to that version before continuing.

Second thing to check: have you enabled auto-dismissing of the thanks view? It's off by default. To enable it, you should set the `prompt_view_thanks_display_time_ms` attribute in your prompt view xml, like so:

```xml
<com.github.stkent.amplify.prompt.DefaultLayoutPromptView
    android:id="@+id/prompt_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    ...
    app:prompt_view_thanks_display_time_ms="2000" />
```

or, if you are configuring the prompt view in code, call `setThanksDisplayTimeMs` when configuring your `BasePromptViewConfig.Builder` instance:

```java
final BasePromptViewConfig basePromptViewConfig
        = new BasePromptViewConfig.Builder()
                // ...
                .setThanksDisplayTimeMs(2000)
                .build();
```

Let me know if either of those suggestions fixes your issue, and if not, we'll dig deeper :-)

**Comment by jamieomatthews** [comment]
app:prompt_view_thanks_display_time_ms="2000" fixed this for me.  Thanks!!

**Comment by stkent** [comment]
Awesome, glad to hear it!

**Comment by jamieomatthews** [comment]
Should 2000 ms be the default?  Or is it a common case that people don't want this to auto close?  Just a suggestion.  Thanks again for helping!

**Comment by stkent** [comment]
In our own apps, the prompt is typically located at the end of some user-driven flow (e.g. when a purchase is completed), so there are few other actions available to keep the user on that screen for very long. Setting a default would also mean a slightly gnarly API: you'd want to be able to change the dismiss time (to e.g. 1000ms) but also to be able to disable dismissing entirely... which could effectively be achieved by setting a dismiss time of `MAX_INT` ms, but I'm not a huge fan of that!
