### ISSUE TITLE
Allow other critical feedback behaviors

### ISSUE THREAD

**Issue by adrien-aubel** [stkent/amplify#159]
It would be great if we could override the current critical feedback behavior that opens the mail client.

Simply allowing custom listeners or a callback system would be enough I think.

Offering a listener API would also allow more custom behaviors, log analytics, ...

**Comment by stkent** [comment]
Yep, I've been thinking about this. I need to figure out a clean API for swapping out the email client for something else, but once I've done that this should be a quick change.
