### ISSUE TITLE
Am I doing it right?

### ISSUE THREAD

**Issue by JEKos** [stkent/amplify#174]
Hi, I'm using amplify in my app, with the below settings, but I don't see it, even it has been passed over 5 days. I don't have applied the settings?

```java
Amplify.initSharedInstance(this)
       .setPositiveFeedbackCollectors(new GooglePlayStoreFeedbackCollector())
       .setCriticalFeedbackCollectors(new BaseEmailFeedbackCollector("feedback@mydomain.com") {
           @NonNull
           @Override
           protected String getSubjectLine(@NonNull IApp iApp, @NonNull IEnvironment iEnvironment, @NonNull IDevice iDevice) {
               return "Feedback for My App";
           }
           @NonNull
           @Override
           protected String getBody(@NonNull IApp iApp, @NonNull IEnvironment iEnvironment, @NonNull IDevice iDevice) {
               return null;
           }
       })
       .addEnvironmentBasedRule(new GooglePlayStoreRule()) // Prompt never shown if Google Play Store not installed.
       .setInstallTimeCooldownDays(5)   // Prompt not shown within 5 days of initial install.
       .setLastUpdateTimeCooldownDays(3) // Prompt not shown within 3 days of most recent update.
       .setLastCrashTimeCooldownDays(7) // Prompt not shown within one week of most recent crash.
       .addTotalEventCountRule(PromptInteractionEvent.USER_GAVE_POSITIVE_FEEDBACK,
               new MaximumCountRule(1)) // Never ask the user for feedback again if they already responded positively.
       .addTotalEventCountRule(PromptInteractionEvent.USER_GAVE_CRITICAL_FEEDBACK,
               new MaximumCountRule(1)); // Never ask the user for feedback again if they already responded critically.
```

**Comment by stkent** [comment]
Hi @JEKos!

At a glance, your configuration there looks good. The only thing I'd advise against is returning `null` in the `getBody` method - that method expects a non-null result (as indicated by the annotation), so a safer option if you want no default body would be to return an empty string, `""`. However, I doubt that is causing the issue.

If you could provide the following bits of information, that would help me figure out what's going on!

1. The code where you call the `promptIfReady` method (see step 4 of [Getting Started](https://github.com/stkent/amplify#getting-started))
2. The version of Amplify you are using

Hopefully we'll be able to get to the bottom of this quickly :)

**Comment by JEKos** [comment]
Thanks for the reply!
1. I have already added this to my prefer fragment I want to show it
2. I'm using the latest version (2.1.0)

**Comment by stkent** [comment]
Awesome! Can you please post the code snippet for answer 1. Thanks!

**Comment by JEKos** [comment]
Sure, here:
```
if (savedInstanceState == null) {
                DefaultLayoutPromptView promptView
                        = (DefaultLayoutPromptView)rootView.findViewById(R.id.prompt_view);


                final BasePromptViewConfig basePromptViewConfig
                        = new BasePromptViewConfig.Builder()
                        .setUserOpinionQuestionTitle("Do you like MyApp?")
                        .setUserOpinionQuestionPositiveButtonLabel("Yeah!")
                        .setUserOpinionQuestionNegativeButtonLabel("Nah")
                        .setPositiveFeedbackQuestionTitle("Awesome! Would you like to rate it?")
                        .setPositiveFeedbackQuestionSubtitle("It helps a lot :)")
                        .setPositiveFeedbackQuestionPositiveButtonLabel("Sure!")
                        .setPositiveFeedbackQuestionNegativeButtonLabel("Not right now")
                        .setCriticalFeedbackQuestionTitle(":( Would you like to send feedback?")
                        .setCriticalFeedbackQuestionPositiveButtonLabel("Sure!")
                        .setCriticalFeedbackQuestionNegativeButtonLabel("Not right now")
                        .setThanksTitle("Thank you! You rock!!!!")
                        .build();

                final DefaultLayoutPromptViewConfig defaultLayoutPromptViewConfig
                        = new DefaultLayoutPromptViewConfig.Builder()
                        .setForegroundColor(getResources().getColor(R.color.MyTheme_Toolbar_TextColor))
                        .setBackgroundColor(getResources().getColor(R.color.MyTheme_Toolbar))
                        .setTitleTextColor(getResources().getColor(R.color.MyTheme_Toolbar_TextColor))
                        .setSubtitleTextColor(getResources().getColor(R.color.MyTheme_Toolbar_TextColor))
                        .setPositiveButtonTextColor(getResources().getColor(R.color.MyTheme_Toolbar_TextColor))
                        .setPositiveButtonBackgroundColor(getResources().getColor(R.color.MyTheme_Toolbar))
                        .setPositiveButtonBorderColor(getResources().getColor(R.color.MyTheme_Toolbar_TextColor))
                        .setNegativeButtonTextColor(getResources().getColor(R.color.MyTheme_Toolbar_TextColor))
                        .setNegativeButtonBackgroundColor(getResources().getColor(R.color.MyTheme_Toolbar))
                        .setNegativeButtonBorderColor(getResources().getColor(R.color.MyTheme_Toolbar_TextColor))
                        .build();

                promptView.applyBaseConfig(basePromptViewConfig);
                promptView.applyConfig(defaultLayoutPromptViewConfig);
                Amplify.getSharedInstance().promptIfReady(promptView);
```

**Comment by stkent** [comment]
Hmm, nothing looks out of place there... A few more questions:

- Have you [enabled logging](https://github.com/stkent/amplify#logging)? That might provide some clues.
- Is this code deployed to production or still in development? (Trying to ascertain how much control we have to experiment with.)
- If in production; do you have crash reporting tools available? If your app is crashing a lot, the crash cooldown could be preventing the prompt from showing even after five days have elapsed. (Remember that _all_ rules must be satisfied simultaneously for the prompt to show. That's something I'd like to make more flexible in the future.)
- Do you have analytics on your preferences fragment? Could it just be that traffic to that part of your app is very low, so no-one has met all the conditions yet?

**Comment by JEKos** [comment]
• No
• In production
• Yes
• Yes, but is not preference fragment, My app is using navigation drawer,  so a lot of my things are in fragments.

I will try it again with a clean install on my phone and shorter time for days to see if will appears. Thanks for your help! :)

**Comment by stkent** [comment]
No problem! Check back in here once you've tried those steps you mention. If you're still having trouble, I can put together a test version of the library that allows cooldown times in seconds to make it much easier to debug rapidly.

**Comment by JEKos** [comment]
Yep, it's working. Sorry for opening an issue. Thanks!

p.s amplify is available for iOS (Swift/Obj C) ?

**Comment by stkent** [comment]
No worries, glad whatever it was got straightened out!

Regarding iOS: I know there's at least a partial version floating around at Detroit Labs (where I work). Let me ask around...

**Comment by JEKos** [comment]
Any news about iOS version?

**Comment by stkent** [comment]
Thanks for the reminder! I checked in with my colleagues who confirmed that there is an internal version of this library circulating, written in Objective-C, but no open source version. I suspect that it is unlikely that an open source version will be made available any time soon, unfortunately. Sorry!
