### ISSUE TITLE
amplify doesn't stop after you press No.

### ISSUE THREAD

**Issue by johncodeos** [stkent/amplify#177]
Hi!
I notice when the user press the negative button and ends this back-to-back questions about if he wants to send a feedback etc. After that if he goes again to the current page e.g NewsActivity without closing the app, amplify starts again to ask him if he want to leave a feedback or not. How can I stop this.

**Comment by stkent** [comment]
Based on what you describe, it sounds like you should update your `Amplify` configuration to include a rule based on the [`PromptInteractionEvent. USER_DECLINED_FEEDBACK `](https://github.com/stkent/amplify/blob/2.1.0/amplify/src/main/java/com/github/stkent/amplify/tracking/PromptInteractionEvent.java#L35) event. If you're using the default rules, the user should only need to dismiss once per app version. Let me know if that doesn't answer your question!

**Comment by JEKos** [comment]
I checked it. But it still the same, i think PromptInteractionEvent. USER_DECLINED_FEEDBACK is for when the user has closed the app and you don't want to bother him again.To problem is amplify re-run again when you press the same activity, even you rated the app (I just tested). I think this can be fixed with sharedPreferences, right?

**Comment by stkent** [comment]
I think I'm not understanding exactly. Just to make sure we're on the same page:

1) The user is prompted
2) The user clicks "no, I'm not enjoying the app"
3) The user agrees to give feedback
4) The user sends a feedback email
5) The user returns to the app
6) Amplify begins the prompt sequence from the beginning again

Is that sequence correct?

**Comment by JEKos** [comment]
Yeah, but when the user want to send a email, if he doesn't want to send and feedback at all, Amplify begins the prompt sequence from the beginning again if he press the same activity from the app's menu.

**Comment by stkent** [comment]
Ok, so is this right?

1) The user is prompted
2) The user clicks "no, I'm not enjoying the app"
3) The user declines to give feedback
4) The user leaves the activity where they were prompted
5) The user returns to a new instance of the activity they just left
6) Amplify begins the prompt sequence from the beginning again

?

**Comment by JEKos** [comment]
No, the steps are

1. The user is prompted
2. The user clicks "no, I'm not enjoying the app" , or he click "yes, I'm not enjoying the app" and he goes to rate the app on google play store (then skip the 3rd and 4th step)
3. The user agrees to give feedback, or he doesn't agree 
4. The user sends a feedback email
**5. The user returns to the app
7. The user goes to another activity e.g Photos from the menu of the app
8. The user goes back again to the activity e.g News and the amplify starts again**

**Comment by JEKos** [comment]
No, the steps are

1. The user is prompted
2. The user clicks "no, I'm not enjoying the app" , or he click "yes, I'm not enjoying the app" and he goes to rate the app on google play store (then skip the 3rd and 4th step)
3. The user agrees to give feedback, or he doesn't agree 
4. The user sends a feedback email
**5. The user returns to the app
7. The user goes to another activity e.g Photos from the menu of the app
8. The user goes back again to the activity e.g News and the amplify starts again**

**Comment by stkent** [comment]
Ok, gotcha. Can you please post the code where you initialize your `Amplify` instance (probably in your `Application` class) and the code where you call `promptIfReady` from the News `Activity`? Thanks!

**Comment by JEKos** [comment]
**Amplify initialize**

```
Amplify.initSharedInstance(this)
                .setPositiveFeedbackCollectors(GooglePlayStoreFeedbackCollector())
                .setCriticalFeedbackCollectors(object : BaseEmailFeedbackCollector("feedback@myemail.com") {
                    override fun getSubjectLine(iApp: IApp, iEnvironment: IEnvironment, iDevice: IDevice): String =
                            "Feedback for My App"

                    override fun getBody(iApp: IApp, iEnvironment: IEnvironment, iDevice: IDevice): String =
                            ""
                })
                .addEnvironmentBasedRule(GooglePlayStoreRule()) // Prompt never shown if Google Play Store not installed.
                .setInstallTimeCooldownDays(5)   // Prompt not shown within 5 days of initial install.
                .setLastUpdateTimeCooldownDays(3) // Prompt not shown within 3 days of most recent update.
                .setLastCrashTimeCooldownDays(7) // Prompt not shown within one week of most recent crash.
                .addTotalEventCountRule(PromptInteractionEvent.USER_GAVE_POSITIVE_FEEDBACK,
                        MaximumCountRule(1)) // Never ask the user for feedback again if they already responded positively.
                .addTotalEventCountRule(PromptInteractionEvent.USER_GAVE_CRITICAL_FEEDBACK,
                        MaximumCountRule(1)) // Never ask the user for feedback again if they already responded critically.
                .addTotalEventCountRule(PromptInteractionEvent.USER_DECLINED_FEEDBACK,
                        MaximumCountRule(1)) 
```

**And from the News Activity (btw it's a fragment)**

```
if (savedInstanceState == null) {
            val promptView: DefaultLayoutPromptView = rootView.findViewById(R.id.prompt_view)

            val basePromptViewConfig = BasePromptViewConfig.Builder()
                    .setUserOpinionQuestionTitle("Do you like MyApp?")
                    .setUserOpinionQuestionPositiveButtonLabel("Yeah!")
                    .setUserOpinionQuestionNegativeButtonLabel("Nah")
                    .setPositiveFeedbackQuestionTitle("Awesome! Would you like to rate it?")
                    .setPositiveFeedbackQuestionSubtitle("It helps a lot :)")
                    .setPositiveFeedbackQuestionPositiveButtonLabel("Sure!")
                    .setPositiveFeedbackQuestionNegativeButtonLabel("Not right now")
                    .setCriticalFeedbackQuestionTitle(":( Would you like to send feedback?")
                    .setCriticalFeedbackQuestionPositiveButtonLabel("Sure!")
                    .setCriticalFeedbackQuestionNegativeButtonLabel("Not right now")
                    .setThanksTitle("Thank you!")
                    .build()

val defaultLayoutPromptViewConfig = DefaultLayoutPromptViewConfig.Builder()
       .setForegroundColor(ContextCompat.getColor(context,R.color.Toolbar_TextColor))
       .setBackgroundColor(ContextCompat.getColor(context,R.color.Toolbar))
       .setTitleTextColor(ContextCompat.getColor(context,R.color.Toolbar_TextColor))
       .setSubtitleTextColor(ContextCompat.getColor(context,R.color.Toolbar_TextColor))
       .setPositiveButtonTextColor(ContextCompat.getColor(context,R.color.Toolbar_TextColor))
       .setPositiveButtonBackgroundColor(ContextCompat.getColor(context,R.color.Toolbar))
       .setPositiveButtonBorderColor(ContextCompat.getColor(context,R.color.Toolbar_TextColor))
       .setNegativeButtonTextColor(ContextCompat.getColor(context,R.color.Toolbar_TextColor))
      .setNegativeButtonBackgroundColor(ContextCompat.getColor(context,R.color.Toolbar))
      .setNegativeButtonBorderColor(ContextCompat.getColor(context,R.color.Toolbar_TextColor))
      .build()


                promptView.applyBaseConfig(basePromptViewConfig)
                promptView.applyConfig(defaultLayoutPromptViewConfig)
                Amplify.getSharedInstance().promptIfReady(promptView)
}
```

**Comment by stkent** [comment]
Looks good after a quick scan; I'll dig in more later today and see if I can spot anything.

**Comment by stkent** [comment]
Nothing obviously looks out of place here. I'm afraid I'd need to be able to play with actual code that reproduces this issue to offer any more suggestions. Is this codebase something you can share?

**Comment by JEKos** [comment]
I'll make a demo app and I'll share it with you

**Comment by stkent** [comment]
Perfect, thanks!

**Comment by JEKos** [comment]
Hey, I made the [demo](https://github.com/JEKos/AmplifyDemoForFix) app.
When the user press yes or no and the rating ends and then he press Refresh Activity, it shows again the rating from the beginning. So what I think is, when the user ends the rating, you need to add a boolean sharedPreference to true, and check it every time the Activity or Fragment called. Amplify now is checking only when it the app is launching. Also may I create a pull request with a UI fix for the amplify? It's very important. Buttons doesn't show correctly for devices with <=17 API

**Comment by stkent** [comment]
Thanks! I'm a bit confused - I can't see what's different about your copy of the repository. Where did you make the changes, and how do I build the demo app?

**Comment by JEKos** [comment]
Hi, yeah, probably I copied your demo instead of mine. I'll fix it

**Comment by stkent** [comment]
Cool, comment back here when updated so I see it, thanks!
