### ISSUE TITLE
What happens if the user doesn't respond to the prompts?

### ISSUE THREAD

**Issue by svenoaks** [stkent/amplify#184]
With the default rules, what happens if the user does not respond to any prompts (for instance, the app may not be translated into the user's language)?. Does the library hide the prompt after a certain number of times being created? Is there a rule to control this?

**Comment by stkent** [comment]
Hi @svenoaks!

The default rules do not limit how many times the prompt will be shown to any given user.

Nevertheless, this behavior can be achieved quite quickly by combining a built-in `MaximumCountRule` rule with the built-in `PROMPT_SHOWN` event. Your configuration would look something like this, with the _last_ line being the one that adds the behavior you describe:

```
Amplify.initSharedInstance(this)
       .setPositiveFeedbackCollectors(new GooglePlayStoreFeedbackCollector())
       .setCriticalFeedbackCollectors(new DefaultEmailFeedbackCollector("someone@example.com"))
       .applyAllDefaultRules()
       .addTotalEventCountRule(PromptViewEvent.PROMPT_SHOWN, new MaximumCountRule(10));
```

(I typed this^ without an IDE to hand, so please forgive any typos.)

Let me know if that works for you, or if you run into any trouble using it. Thanks!

Stuart

**Comment by svenoaks** [comment]
That should be good, thanks.
