### ISSUE TITLE
Add default layout customization hook: button height

### ISSUE THREAD

**Issue by anastasia-zaitsewa** [stkent/amplify#186]
Hi there!

It seems that both feedback buttons have minHeight [set to a fixed value](https://github.com/stkent/amplify/blob/master/amplify/src/main/res/layout/default_question_view.xml#L56) of [48dp](https://github.com/stkent/amplify/blob/master/amplify/src/main/res/values/dimens.xml#L23) (126px on the screenshot). Here is a screenshot from layout inspector:
<img width="674" alt="Screenshot 2019-07-24 at 17 00 03" src="https://user-images.githubusercontent.com/3982686/61804682-a027b500-ae34-11e9-82ef-171012889c36.png">

This leads to a visually weird UI if you will choose a small type face (for example 12sp) but the button height stays at its minimal size.

Would be nice to have an option to change this setting and allow customizable min button height.

**Comment by stkent** [comment]
Hi @anastasia-zaitsewa!

The default layout uses a minimum button height of 48dp to guarantee that the buttons meet the minimum touch target guidelines (https://material.io/design/usability/accessibility.html#layout-typography).

In theory it would be possible for Amplify's default layout to accommodate visually smaller buttons but preserve a 48dp-tall touch target by nesting the buttons inside a `FrameLayout`, or using a [`TouchDelegate`](https://developer.android.com/reference/android/view/TouchDelegate.html), or something similar. However, that level of complexity seems higher than most consumers of the library need or want, so I'm hesitant to include it.

If this is still something you want to explore, it should be possible with the current version of the library - it will just require a little more work. [This section of the README](https://github.com/stkent/amplify#custom-layout) describes how to use your own question layout with Amplify. If desired, you could create a layout that mimics the default question layout, just with shorter buttons. Let me know if that's an acceptable option for you, and if you need any help with the implementation :)

Best,

Stuart

**Comment by anastasia-zaitsewa** [comment]
@stkent Hi there!

I guess setting the minimal button height per guides is a valid point. I am closing this issue.

P.S.: Nice library overall!
