### ISSUE TITLE
Allow multiple Amplify instances backed by different shared preferences

### ISSUE THREAD

**Issue by mwajeeh** [stkent/amplify#193]
We want to collect feedback for different features in our app and it would be nice if we could configure it feature based. E.g. Someone is using feature A, we track it and after high usage ask if they are liking it. Once they start using Feature B, a different prompt for feature B shows up.

**Comment by mwajeeh** [comment]
And I think this very low hanging fruit for such a powerful tool.

**Comment by stkent** [comment]
I like this idea! Unfortunately I think the effort involved is quite high; going from 1->many instances is often as much work as going from 0->1, especially when I'd like to keep the usage as simple as possible for default (single instance) use cases.

I don't have time to explore this, but feel free to fork the library and adapt it to support multiple instances if you want to :)

**Comment by mwajeeh** [comment]
I will definitely explore more. Initially I thought we can replace
`private static Amplify sharedInstance;`

with 

`private static Map<String, Amplify> sharedInstances`

where String will be `backingSharedPreferencesName` and then modifying
`public static Amplify getSharedInstance()`
to 
`public static Amplify getDefaultSharedInstance()`
and introducing
`public static Amplify getSharedInstance(backingSharedPreferencesName)`
will work. 
I will explore more as I don't know the much about internal working of library. My understanding was that everything is scoped to `backingSharedPreferencesName`.

**Comment by mwajeeh** [comment]
This way I can do 
```
Amplify.getSharedInstance("video_call_feature");
Amplify.getSharedInstance("sms_feature");
```
