### ISSUE TITLE
Allow calling In-App Review API

### ISSUE THREAD

**Issue by alexeyvasilyev** [stkent/amplify#194]
Recently Google introduced API for in-app review
https://android-developers.googleblog.com/2020/08/in-app-review-api.html

The main problem with that API that there is no guarantee that in-app review dialog will be shown. I have created a FeedbackCollecter to test that. I see that both task2.isSuccessful and task2.isComplete are true (see code below), but no dialog review shown (app published to Google Play, previous review empty). It is written by Google that 

> We believe the best time to prompt your users is when they have used the app enough to be able to provide thorough and useful feedback

I guess review is shown after sometime of app use only. So my request to redesign Amplify API slightly to not asking for review and allow its use without any UI, but allow ReviewManager API to be called.

Something like this:

```
Amplify.initSharedInstance(this)
                .setLastUpdateTimeCooldownDays(7)
                .setLastCrashTimeCooldownDays(4)
                .setReviewCollectors(new GooglePlayStoreInAppReviewFeedbackCollector())
                .askForReviewIfReady()

```

```
   implementation 'com.google.android.play:core:1.8.0' // Google Play in-app review
  ...
    class GooglePlayStoreInAppReviewFeedbackCollector implements IFeedbackCollector {

        @Override
        public boolean tryCollectingFeedback(@NonNull Activity activity, @NonNull IApp iApp, @NonNull IEnvironment iEnvironment, @NonNull IDevice iDevice) {
            Log.d(TAG, "Requesting in-app review");
            ReviewManager manager = new FakeReviewManager(activity);
//            ReviewManager manager = ReviewManagerFactory.create(activity);
            Task<ReviewInfo> request = manager.requestReviewFlow();
            request.addOnCompleteListener(task -> {
                if (task.isSuccessful()) {
                    Log.d(TAG, "Requesting in-app review succeeded");
                    // We can get the ReviewInfo object
                    ReviewInfo reviewInfo = task.getResult();
                    Task<Void> flow = manager.launchReviewFlow(activity, reviewInfo);
                    flow.addOnCompleteListener(task2 -> {
                        Log.i(TAG, "Requesting in-app review isSuccessful: " + task2.isSuccessful());
                        Log.i(TAG, "Requesting in-app review isComplete: " + task2.isComplete());
                        // The flow has finished. The API does not indicate whether the user
                        // reviewed or not, or even whether the review dialog was shown. Thus, no
                        // matter the result, we continue our app flow.
                    });
                } else {
                    // There was some problem, continue regardless of the result.
                    Log.e(TAG, "Requesting in-app review failed");
                }
            });
            return false;
        }
    }
```

**Comment by stkent** [comment]
Thanks for the thoughts! I linked this from the existing tracking issue #187 so it can be easily referenced later. I will close this new issue now and continue using #187 to represent this idea.

**Comment by peterdk** [comment]
The Google docs clearly state that 'Your app should not ask the user any questions before or while presenting the rating button or card, including questions about their opinion (such as “Do you like the app?”) or predictive questions (such as “Would you rate this app 5 stars”).' So I think using Amplify with the API is not allowed.

**Comment by stkent** [comment]
@peterdk you are correct; only the "rules engine" part of Amplify could be used with the in-app prompt. The question flow would be skipped to adhere to that guideline!
