### ISSUE TITLE
Remove the word "Bummer" from the default prompt

### ISSUE THREAD

**Issue by svenoaks** [stkent/amplify#195]
We have got a couple reviewers who went through the trouble to leave a 1-star rating because they thought we were insulting or cursing at them (calling them a "loafer or vagrant", presumably). Also, had it professionally translated it in a few languages and sometimes get the same problem.

This should probably read "Sorry, would you like to leave feedback?"

**Comment by stkent** [comment]
@svenoaks I updated that question to read

> Oh no! Would you like to send feedback?

Thanks for this great feedback; my colloquial understanding of the term didn't properly account for how others might interpret it. <3

Please update to v2.2.3 to get the new question wording and let me know if you see any issues.
