### ISSUE TITLE
Enable/disable build failures due to checker violations based on build environment

### ISSUE THREAD

**Issue by stkent** [stkent/amplify#55]
Fail local builds when running `./gradlew check` if any of the checker plugins report violations.

**Comment by stkent** [comment]
@btkelly pretty sure this feature has made it into Gnag now, right?

**Comment by stkent** [comment]
cc @btkelly does `checkLocal` resolve this? I think it does?

**Comment by btkelly** [comment]
Yup, the checkLocal task will check all the same things and fail the build locally
